
java_library(
    name = "actionProcessors",
    srcs = [
        "ActionProcessor.java",
        "PassActionProcessor.java",
        "BetActionProcessor.java",
        "RoseActionProcessor.java",
        "SkullActionProcessor.java",
    ],
    deps = [
        "//main:protoJava",
    ],
    visibility = ["//visibility:public"],
)