
java_library(
    name = "di",
    srcs = [
        "ActionProcessorModule.java",
        "AppComponent.java",
    ],
    deps = [
        "//main/action:actionProcessors",
         "//deps/dagger:dagger",
    ],
    visibility = ["//visibility:public"],
)